### ISSUE TITLE
Version 4.2 no longer works on Heroku, while 3.2 did

### ISSUE THREAD

**Issue by shepmaster** [rustyhorde/vergen#54]
Not sure what details would be most useful to share, but this is the error message:

```
Git2(Error { code: -3, klass: 6, message: "could not find repository from \'.\'" })
```

**Comment by CraZySacX** [comment]
Interesting.  I'll have to try to reproduce.  The change here is switching from git `Command`s over to using `git2`.   I'm using `Repository::discover` and that seems like where that failure is happening.

**Comment by CraZySacX** [comment]
I looked into this over the weekend.  The TLDR is I don't think that `vergen` has ever "worked" on Heroku.   

The 4.x version errors out because the source directory out on Heroku is not a valid git directory (there is no .git directory).    The 3.x version doesn't error, but the failure on the `git rev-parse HEAD` command would produce "UNKNOWN" as the value.   Looking at how you used it, I would expect your USER-AGENT string to have that "UKNOWN" string in it when run out on Heroku.   I'm haven't used Heroku in a few years, so this testing was done with a git deploy.   If there is another method to deploy that does end up with a valid git directory, then either version should work.

As for solutions, if you don't need the SHA locally, then I would just drop vergen and use a simple println in your build.rs using the Heroku supplied `SOURCE_VERSION` environment variable.   If you do need it locally, then something like the following would likely work.

````
Ok(if let Ok(stack) = env::var("STACK") {
    if stack.starts_with("heroku") {
        if let Ok(source_version) = env::var("SOURCE_VERSION") {
            println!("cargo:rustc-env=VERGEN_SHA={}", source_version);
        }
    }
} else {
    vergen(Config::default())?
})
````

**Comment by shepmaster** [comment]
Heh, that's totally believable; I never actually _looked_ to see what the calculated value was. Sounds like the library now produces a better result (loud error instead of silent error) and it's on me to make some choices.

Thanks!

**Comment by shepmaster** [comment]
Minor nit for anyone reading this in the future:

```diff
-             println!("cargo:rustc-env=VERGEN_SHA={}", source_version);
+             println!("cargo:rustc-env=VERGEN_GIT_SHA={}", source_version);
```
