### ISSUE TITLE
Report git dirty state

### ISSUE THREAD

**Issue by TilBlechschmidt** [rustyhorde/vergen#59]
It'd be cool if we could have the git dirty state available too.

Personally, I like to include the following info in my version strings:

- Git tag (if the repository is on one right now)
- Commit and branch if we are not on a tag
- `-dirty` postfix if our working directory had changes

Turning into one of these:
```
v0.2.0
v0.2.0-dirty
2c12d1b
2c12d1b-dirty
```

Side request: Make it configurable to not use `CARGO_PKG_VERSION` or use something else (e.g. the commit) as a fallback for the git tag.

**Comment by TilBlechschmidt** [comment]
Since Rust has [`option_env!`](https://doc.rust-lang.org/std/macro.option_env.html) we could just leave `VERGEN_GIT_SEMVER` unset if the repository is not on a git tag.

**Comment by TilBlechschmidt** [comment]
Actually, exactly the functionality I described is available through the `git describe` operation (which is also exposed through the `git2` crate).

By using something a little bit like this:
```rust
let repository = Repository::open(&repo_dir).unwrap();

let mut describe_opts = DescribeOptions::new();
describe_opts.describe_tags();

let mut describe_format_opts = DescribeFormatOptions::new();
describe_format_opts.dirty_suffix("-dirty");

let description = repository.describe(&describe_opts).unwrap();
let version = description.format(Some(&describe_format_opts)).unwrap();
```

We could get both the most recent tag, the number of commits since the tag, the current commit hash if we are not directly on a tag, and the dirty state.

**Comment by CraZySacX** [comment]
The current output for `VERGEN_GIT_SEMVER` looks like `5.0.1-6-g40f762e`.  Includes commits since last tag and the current commit hash.   Are you requesting the ability to also add the `-dirty` suffix to this?

As for not having `VERGEN_GIT_SEMVER` set, that's a breaking change.  I agree that it could probably should remain unset if you don't have a tag, but there is history on this output.

I do like the idea of a fallback strategy of some sort.   Default progresses from tag -> commit only -> pkg version.    Then make the fallback strategy a choice.

**Comment by TilBlechschmidt** [comment]
It basically boils down to having a flag which enables the `-dirty` suffix, yes.

I wasn't aware that the `git describe` command can output the commits since the last tag initially. It makes this a whole lot simpler.

**Comment by teor2345** [comment]
#29 used to add dirty, maybe it was removed during a major version upgrade?
